### ISSUE TITLE
Manage member types thanks to xProfile component

### ISSUE THREAD

**Issue by imath** [CFCommunity-net/buddypress-group-restrictions#6]
See https://github.com/CFCommunity-net/bp-mt-extended/issues/1

1/ Create a specific new Field type to manage member types in xProfile Field Admin UI : 
![xprofile-field](https://cloud.githubusercontent.com/assets/1834524/6998063/75941ef0-dbd4-11e4-8307-c63e00fabceb.png)

2/ Include a migration tool

> if the field that where containing the options used to type members is edited in favor of the new Member type field, then it will be possible using WP Admin > Tools > BuddyPress to migrate the field data as member types.

**Comment by imath** [comment]
NB: don't use this plugin with BP MT Extended activated, else nothing will happen.

**Comment by BoweFrankema** [comment]
Thanks a lot for you work on this imath, it's a very elegant solution to the problem. Sadly though there are a few issues related to how I've set up the site that I need to find a solution for. Both problems are related to not saving the xprofile value but saving it as a member type.

I'm relying on Brajesh (Buddydev) his conditional profile fields plugin to show/hide profile fields based on xProfile value (relationship with CF). https://github.com/sbrajesh/conditional-profile-fields-for-buddypress

Another similar issue is using checks to see if a user has completed his profile as I'm doing here: https://github.com/CFCommunity-net/cfcommunity/blob/master/wp-content/themes/cfcommunity/lib/buddypress/bp-hooks.php#L262. 

The 2nd problem should be easy to fix by checking for a member type instead of a xprofile field value. The first problem is harder. We would have to show a certain xprofile field based on Member Type similar to Brajesh his plugin. If this makes things too crazy, the easiest (but ugly solution) would be to still save the xprofile field value as well as the member type. Unless you or @henrywright have any other brilliant solutions :-)

**Comment by imath** [comment]
Too bad :(

I guess the easiest way is to duplicate the member type in the xProfile data. That is to say remove the code i was using to prevent it :)

imath.
http://profiles.wordpress.org/imath/

**Comment by BoweFrankema** [comment]
Yeah.. it's not super elegant but for it's not a disaster either. And the good thing is that besides that everything is working as it should! Could you maybe uncomment/abstract the code you used to prevent the saving of the field?
